version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  eureka-server:
    build: ./eureka-server
    restart: on-failure
    env_file: ./.env
    ports:
      - $EUREKA_SERVER_LOCAL_PORT:$EUREKA_SERVER_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  account-service:
    depends_on:
      - mysqldb
      - eureka-server
    build: ./account-service
    restart: on-failure
    env_file: ./.env
    ports:
      - $ACCOUNT_SERVICE_LOCAL_PORT:$ACCOUNT_SERVICE_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}},
        "spring.datasource.url":"jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  transaction-service:
    depends_on:
      - mysqldb
      - eureka-server
    build: ./transaction-service
    restart: on-failure
    env_file: ./.env
    ports:
      - $TRANSACTION_SERVICE_LOCAL_PORT:$TRANSACTION_SERVICE_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}},
        "spring.datasource.url":"jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: